services:
  postgres:
    image: postgres:17

    container_name: contato_seguro

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: desafiojunior11
      POSTGRES_DB: projetoticket

    ports:
      - "5455:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: